# Example from Material Source: https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

site_name: Read the Docs
site_url: https://readthedocs.showipintbri.com
site_author: Tony E. (@showipintbri)
site_description: >-
  Documentation site for personal reference.
  A place to store all the one liners and how-to's I may need one day.
  Contributions are welcomed!

repo_url: https://github.com/showipintbri/read-the-docs
repo_name: showipintbri/read-the-docs

theme:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - navigation.tracking
  #  - navigation.sections
    - navigation.indexes
  name: material
  favicon: images/favicon.png
  logo: assets/logo.svg
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - Home: 
    - index.md
  - Python:
    - python/index.md
    - Dictionaries: python/dictionaries.md
  - Graylog: 
    - graylog/index.md
    - Field Names: graylog/field_names.md
  - Linux:
    - linux/index.md
    - bash: linux/bash.md
    - CentOS: linux/centos.md
    - rsyslog: linux/rsyslog.md
    - systemctl: linux/systemctl.md
  - Cisco:
    - cisco/index.md
    - Forensics: cisco/forensics.md
    - "Packet Capture: ASA": cisco/capture-asa.md
    - "Packet Capture: 3850": cisco/capture-3850.md
  - Juniper:
    - juniper/index.md
  - Default Credentials:
    - credentials/index.md
  - Tcpdump:
    - tcpdump/index.md
  - Windows:
    - windows/index.md
    - "Packet Capture: netsh": windows/capture-netsh.md
