name: Build mkdocs site 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install mkdocs-material
      - run: mkdocs build --site-dir public
      - name: Git Comands
        run: |
          git add public/
          git commit -m "GitHub Actions"
          git push 
    

